### PR TITLE
PG-373: Remove WAL fields for PG12 and below.

### PR DESCRIPTION
**Pull request by ibrarahmad**

### CODE REVIEW

**Comment by Naeem-Akhter** [comment]
Regression fails on PG-12, needs an update to test case. @ibrarahmad 

`/usr/lib/postgresql/12/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/12/bin'    --temp-config /usr/lib/postgresql/12/lib/pgxs/src/makefiles/../../contrib/pg_stat_monitor/pg_stat_monitor.conf --inputdir=regression --dbname=contrib_regression basic version guc counters relations database error_insert application_name application_name_unique top_query cmd_type error rows tags
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test basic                        ... ok           16 ms
test version                      ... ok           16 ms
test guc                          ... ok          520 ms
test counters                     ... ok          903 ms
test relations                    ... ok           46 ms
test database                     ... ok          273 ms
test error_insert                 ... ok           21 ms
test application_name             ... ok           20 ms
test application_name_unique      ... ok           17 ms
test top_query                    ... ok           18 ms
test cmd_type                     ... ok           21 ms
test error                        ... ok           19 ms
test rows                         ... ok           33 ms
test tags                         ... ok           16 ms

======================
 All 14 tests passed.
======================

rm -rf '/home/postgres/src/pg_stat_monitor_ibrar'/tmp_check
/bin/mkdir -p '/home/postgres/src/pg_stat_monitor_ibrar'/tmp_check
cd ./ && TESTDIR='/home/postgres/src/pg_stat_monitor_ibrar' PATH="/usr/lib/postgresql/12/bin:$PATH" PGPORT='65432' top_builddir='/usr/lib/postgresql/12/lib/pgxs/src/makefiles/../..' PG_REGRESS='/usr/lib/postgresql/12/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress' /usr/bin/prove -I /usr/lib/postgresql/12/lib/pgxs/src/makefiles/../../src/test/perl/ -I ./  t/*.pl
t/001_settings_default.pl ................... ok
t/002_settings_pgsm_track_planning.pl ....... ok
t/003_settings_pgms_extract_comments.pl ..... ok
t/004_settings_pgsm_track.pl ................ ok
t/005_settings_pgsm_enable_query_plan.pl .... ok
t/006_settings_pgsm_overflow_target.pl ...... ok
t/007_settings_pgsm_query_shared_buffer.pl .. ok
t/008_settings_pgsm_histogram_buckets.pl .... ok
t/009_settings_pgsm_histogram_max.pl ........ ok
t/010_settings_pgsm_histogram_min.pl ........ ok
t/011_settings_pgsm_bucket_time.pl .......... ok
t/012_settings_pgsm_max_buckets.pl .......... ok
t/013_settings_pgsm_normalized_query.pl ..... ok
t/014_settings_pgsm_track_utility.pl ........ ok
t/015_settings_pgsm_query_max_len.pl ........ ok
t/016_settings_pgsm_max.pl .................. ok
t/017_execution_stats.pl .................... ok
t/018_column_names.pl ....................... 4/?
#   Failed test 'Compare supported columns names for PG version 12 against expected'
#   at t/018_column_names.pl line 88.

#   Failed test 'Select statement against expected column names'
#   at t/018_column_names.pl line 92.

#   Failed test 'Drop PGSM  Extension'
#   at t/018_column_names.pl line 97.
# Looks like you failed 3 tests of 6.
t/018_column_names.pl ....................... Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/6 subtests
t/019_insufficient_shared_space.pl .......... ok
t/020_buffer_overflow.pl .................... ok
t/021_misc_1.pl ............................. ok
t/022_misc_2.pl ............................. ok
t/023_missing_queries.pl .................... ok
t/024_check_timings.pl ...................... skipped: pg_stat_monitor test cases for versions 12 and below.
t/025_compare_pgss.pl ....................... skipped: pg_stat_monitor test cases for versions 12 and below.
t/026_shared_blocks.pl ...................... skipped: pg_stat_monitor test cases for versions 12 and below.
t/027_local_blocks.pl ....................... skipped: pg_stat_monitor test cases for versions 12 and below.
t/028_temp_block.pl ......................... skipped: pg_stat_monitor test cases for versions 12 and below.

Test Summary Report
-------------------
t/018_column_names.pl                     (Wstat: 768 Tests: 6 Failed: 3)
  Failed tests:  4-6
  Non-zero exit status: 3
Files=28, Tests=282, 249 wallclock secs ( 0.11 usr  0.05 sys + 77.57 cusr 17.79 csys = 95.52 CPU)
Result: FAIL
make: *** [/usr/lib/postgresql/12/lib/pgxs/src/makefiles/pgxs.mk:421: installcheck] Error 1

postgres@pgdg-pg12:~/src/pg_stat_monitor_ibrar$ git log -1
commit 3076d5bf5c845a60ddb513cd2681854528c3e0d6 (HEAD -> PG-373, origin/PG-373)
Author: Ibrar Ahmed <ibrar.ahmed@percona.com>
Date:   Wed Dec 7 15:03:14 2022 +0000

    PG-373: Remove wal fields for PG12 and below.
postgres@pgdg-pg12:~/src/pg_stat_monitor_ibrar$ git status
On branch PG-373
Your branch is up to date with 'origin/PG-373'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	guc.bc
	hash_query.bc
	pg_stat_monitor.bc
	results/
	t/results/
	tmp_check/
	`

**Comment by Naeem-Akhter** [comment]
Regression fails on PG-12, needs an update to test case. @ibrarahmad

 `t/018_column_names.pl ....................... 4/?
#   Failed test 'Compare supported columns names for PG version 12 against expected'
#   at t/018_column_names.pl line 88.

#   Failed test 'Select statement against expected column names'
#   at t/018_column_names.pl line 92.

#   Failed test 'Drop PGSM  Extension'
#   at t/018_column_names.pl line 97.
# Looks like you failed 3 tests of 6.
t/018_column_names.pl ....................... Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/6 subtests`

`postgres@pgdg-pg12:~/src/pg_stat_monitor_ibrar$ git log -1
commit 3076d5bf5c845a60ddb513cd2681854528c3e0d6 (HEAD -> PG-373, origin/PG-373)
Author: Ibrar Ahmed <ibrar.ahmed@percona.com>
Date:   Wed Dec 7 15:03:14 2022 +0000

    PG-373: Remove wal fields for PG12 and below.`

**Comment by ibrarahmad** [comment]
> Regression fails on PG-12, needs an update to test case. @ibrarahmad
> 
> t/018_column_names.pl ....................... 4/? Failed test 'Compare supported columns names for PG version 12 against expected' at t/018_column_names.pl line 88.
> 
> Failed test 'Select statement against expected column names' at t/018_column_names.pl line 92.
> 
> Failed test 'Drop PGSM Extension' at t/018_column_names.pl line 97. Looks like you failed 3 tests of 6. t/018_column_names.pl ....................... Dubious, test returned 3 (wstat 768, 0x300) Failed 3/6 subtests`
> 
> postgres@pgdg-pg12:~/src/pg_stat_monitor_ibrar$ git log -1 commit [3076d5b](https://github.com/percona/pg_stat_monitor/commit/3076d5bf5c845a60ddb513cd2681854528c3e0d6) (HEAD -> PG-373, origin/PG-373) Author: Ibrar Ahmed [ibrar.ahmed@percona.com](mailto:ibrar.ahmed@percona.com) Date: Wed Dec 7 15:03:14 2022 +0000
> 
> ```
> PG-373: Remove wal fields for PG12 and below.`
> ```

I will change output in next PR, cannot change because it depends on three other PRs

**Comment by Naeem-Akhter** [comment]
As per discussion, @ibrarahmad will update the test case in next PR.

**Review by Naeem-Akhter — APPROVED** [review]
Approved.

**Pull request merged**
