### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by ibrarahmad**

### CODE REVIEW

**Comment by ibrarahmad** [comment]
@darkfronza Please resolve conflicts

**Comment by ibrarahmad** [comment]
@darkfronza Please resolve this asap.

**Comment by ibrarahmad** [comment]
@darkfronza can you please fix the coflicts.

**Comment by LenzGr** [comment]
@ibrarahmad I wonder if this PR could be closed, now that the devel branch has been removed? According to @darkfronza , all changes from `devel` had already been merged into the `main` branch.

**Pull request closed without merging**
