### PR TITLE
Fix partition_prune testcase

### PR DESCRIPTION
**Pull request by artemgavrilov**
Fixes https://github.com/percona/pg_stat_monitor/issues/423

`compute_query_id` parameter has special value `regress` that allows `pg_stat_monitor` to have  query identifier but hides it in `EXPLAIN`s to let regression testing pass.

https://www.postgresql.org/docs/current/runtime-config-statistics.html#GUC-COMPUTE-QUERY-ID

### CODE REVIEW

**Review by dAdAbird — APPROVED** [review]

**Comment by Naeem-Akhter** [comment]
@artemgavrilov 

Any reason that in this PR we have this setting only for postgresql-14-build & postgresql-15-build ('compute_query_id = regress). But not for postgresql-16-build where it is still (compute_query_id = off)?  Am i missing something? :)

**Comment by artemgavrilov** [comment]
> @artemgavrilov
> 
> Any reason that in this PR we have this setting only for postgresql-14-build & postgresql-15-build ('compute_query_id = regress). But not for postgresql-16-build where it is still (compute_query_id = off)? Am i missing something? :)

Mmm, all 3 (14/15/16) workflows were edited.
Screenshot 2024-04-09 at 13 58 48

**Comment by Naeem-Akhter** [comment]
> > @artemgavrilov
> > Any reason that in this PR we have this setting only for postgresql-14-build & postgresql-15-build ('compute_query_id = regress). But not for postgresql-16-build where it is still (compute_query_id = off)? Am i missing something? :)
> 
> Mmm, all 3 (14/15/16) workflows were edited. Screenshot 2024-04-09 at 13 58 48

Then I guess, somehow GH was showing me wrong diff of changes. But change is reflected in your working branch. :)

**Review by Naeem-Akhter — APPROVED** [review]
Looks good to me!

**Pull request merged**
