### PR TITLE
PG-215 User Guide updates

### PR DESCRIPTION
**Pull request by nastena1606**
Moved pg_stat_monitor column description and compaison to separate docs

new file: REFERENCE.md
new file: COMPARISON.md

### CODE REVIEW

**Comment by denisok** [comment]
@nastena1606 could you please check, maybe you could merge #82 #122 #125 and close those ones.

**Comment by denisok** [comment]
@nastena1606 in the latest beta-3 I could see different fields for `cmd`:
```
 cmd_type            | integer          |           |          |
 cmd_type_text       | text             |           |          |
```
you have only type and wrong type for it.

**Comment by ibrarahmad** [comment]
@nastena1606  can you please remove conflicts

**Comment by nastena1606** [comment]
Done

**Comment by denisok** [comment]
@nastena1606 :
```
Learn more about using histograms from the usage example.
```

example link doesn't work : https://github.com/percona/pg_stat_monitor/blob/master/docs/USER_GUIDE.md#usage-examples-histogram

**Pull request merged**
