### PR TITLE
PG-518: Internal Functions should NOT be visible in PGSM API.

### PR DESCRIPTION
**Pull request by ibrarahmad**

### CODE REVIEW

**Comment by Naeem-Akhter** [comment]
There is no new column named, hex_to_decimal2, in the functions. Secondly there are 14 functions being shown against 3 given in the docs. 

Please refer to details in https://jira.percona.com/browse/PG-518.

**Comment by ibrarahmad** [comment]
> There is no new column named, hex_to_decimal2, in the functions. Secondly there are 14 functions being shown to superuser against 3 given in the docs.
> 
> Please refer to details in https://jira.percona.com/browse/PG-518.

Superusers can see everything. and

**Comment by Naeem-Akhter** [comment]
As per discussion with Ibrar on supported column names in PGSM: 

Following is the expected shown API for Superuser. 
- pg_stat_monitor_reset   
- pg_stat_monitor_version 
- histogram               
- range                   
- get_cmd_type            
- pg_stat_monitor_settings
- decode_error_level      
- pg_stat_monitor_internal
- get_histogram_timings   
- pgsm_create_view        
- pgsm_create_11_view     
- pgsm_create_13_view     
- pgsm_create_14_view     
- pgsm_create_15_view

Following is the expected shown API for non-superuser. 
- pg_stat_monitor_reset   
- pg_stat_monitor_version 
- histogram 

@ibrarahmad Please confirm.

**Comment by ibrarahmad** [comment]
> As per discussion with Ibrar on supported column names in PGSM:
> 
> Following is the expected shown API for Superuser.
> 
> * pg_stat_monitor_reset
> * pg_stat_monitor_version
> * histogram
> * range
> * get_cmd_type
> * pg_stat_monitor_settings
> * decode_error_level
> * pg_stat_monitor_internal
> * get_histogram_timings
> * pgsm_create_view
> * pgsm_create_11_view
> * pgsm_create_13_view
> * pgsm_create_14_view
> * pgsm_create_15_view
> 
> Following is the expected shown API for non-superuser.
> 
> * pg_stat_monitor_reset
> * pg_stat_monitor_version
> * histogram
> 
> @ibrarahmad Please confirm.

yes, correct

**Review by Naeem-Akhter — APPROVED** [review]
Looks goods to me!

**Review by Naeem-Akhter — CHANGES_REQUESTED** [review]
No need to resolve anything now. 

Issue is already fixed on Pg-11 & 12. Tested using https://github.com/ibrarahmad/pg_stat_monitor/tree/PGSM-518.

postgres=# set role u1;
postgres=> SELECT routine_schema, routine_name , routine_type, data_type FROM information_schema.routines WHERE routine_schema = 'public' COLLATE "C";
routine_schema | routine_name | routine_type | data_type
----------------+-------------------------+--------------+-----------
public | pg_stat_monitor_reset | FUNCTION | void
public | pg_stat_monitor_version | FUNCTION | text
public | histogram | FUNCTION | record
(3 rows)

**Review by Naeem-Akhter — APPROVED** [review]

**Pull request merged**
