### PR TITLE
PG-462: adding PG15 build to our workflows

### PR DESCRIPTION
**Pull request by capri1989**
Signed-off-by: Kai Wagner <kai.wagner@percona.com>

### CODE REVIEW

**Comment by capri1989** [comment]
Once https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1979868 that fix made it into the runners image, the check should pass.

**Review by Naeem-Akhter — CHANGES_REQUESTED** [review]
PGSM build is failing with: 
-----------------------------
/usr/bin/install -c -m 755  pg_stat_monitor.so '/usr/lib/x86_64-linux-gnu/postgresql/pg_stat_monitor.so'
/usr/bin/install -c -m 644 .//pg_stat_monitor.control '/usr/share/postgresql/15/extension/'
/usr/bin/install -c -m 644 .//pg_stat_monitor--1.0.sql  '/usr/share/postgresql/15/extension/'
/usr/bin/install: cannot stat './/pg_stat_monitor--1.0.sql': No such file or directory
make: *** [/usr/lib/x86_64-linux-gnu/postgresql/pgxs/src/makefiles/pgxs.mk:237: install] Error 1
Error: Process completed with exit code 2.
----------------------------------------

Before we can enable the PGSM for PG-15, I think DEV need to update the PGSM Makefile to point to right pg_stat_monitor--1.0.sql file to make it work.

**Comment by ibrarahmad** [comment]
Regarding PostgreSQL-15 support for pg_stat_monitor.
1 - We need to add this line to Makefile
```
  ifneq (,$(findstring PostgreSQL15,$(MAJOR)))                   
  CP := $(shell cp pg_stat_monitor--1.0.15.sql.in pg_stat_monitor--1.0.sql)   
 endif

```

It will not work till PostgreSQL-15 GA is released; the current version is 15beta2, which we are not handling here, and there is no need for it

2 - New file SQL file need to be created with the name 
`pg_stat_monitor--1.0.15.sql.in
`

3 - This file needs to have these more columns

  ```
OUT temp_blk_read_time float8,                                             
   OUT temp_blk_write_time float8,                                            
   OUT jit_functions    int8,                                              
   OUT jit_generation_time float8,                                            
   OUT jit_inlining_count int8,                                             
   OUT jit_inlining_time  float8,                                            
   OUT jit_optimization_count int8,                                            
   OUT jit_optimization_time  float8,                                          
   OUT jit_emission_count int8,                                             
   OUT jit_emission_time  float8

```
4 - We need to add support for these columns in pg_stat_monitor.c

We need to copy code from pg_stat_statments and then accommodate it in pg_stat_monitor.

**Comment by capri1989** [comment]
> Regarding PostgreSQL-15 support for pg_stat_monitor. 1 - We need to add this line to Makefile
> 
> ```
>   ifneq (,$(findstring PostgreSQL15,$(MAJOR)))                   
>   CP := $(shell cp pg_stat_monitor--1.0.15.sql.in pg_stat_monitor--1.0.sql)   
>  endif
> ```

That's what I do have in there already or is there something wrong with it?

> 
> It will not work till PostgreSQL-15 GA is released; the current version is 15beta2, which we are not handling here, and there is no need for it
> 
> 2 - New file SQL file need to be created with the name `pg_stat_monitor--1.0.15.sql.in `
> 
That's already there, have you seen it?

> 3 - This file needs to have these more columns
> 
> ```
> OUT temp_blk_read_time float8,                                             
>  OUT temp_blk_write_time float8,                                            
>  OUT jit_functions    int8,                                              
>  OUT jit_generation_time float8,                                            
>  OUT jit_inlining_count int8,                                             
>  OUT jit_inlining_time  float8,                                            
>  OUT jit_optimization_count int8,                                            
>  OUT jit_optimization_time  float8,                                          
>  OUT jit_emission_count int8,                                             
>  OUT jit_emission_time  float8
> ```
> 
Added those columns now to the file, please check again.

> 4 - We need to add support for these columns in pg_stat_monitor.c
> 
> We need to copy code from pg_stat_statments and then accommodate it in pg_stat_monitor.

Can you give me a hint on where exactly I have to look and what I need to take from there?

**Pull request closed without merging**
