### PR TITLE
PG-382: Adjust the maximum value for histogram buckets.

### PR DESCRIPTION
**Pull request by ibrarahmad**
There was no maximum limit set for the number of maximum histograms
bucket, which can lead to a crash in case of higher value.

### CODE REVIEW

**Comment by ibrarahmad** [comment]
I have fix the regression, please review.

**Comment by MichaelDBA** [comment]
Shouldn't this refer to the issue that identified this problem?
https://jira.percona.com/browse/PG-382

**Comment by capri1989** [comment]
Can you please squash the commits and also a lots of tests fail now.

**Comment by ibrarahmad** [comment]
I have already fix the regression, is still failing for you?

**Comment by capri1989** [comment]
> I have already fix the regression, is still failing for you?

I was talking about the tests we have for every PR in this repo. This PR fails before the usual coverall tests, so this one is different:

https://github.com/percona/pg_stat_monitor/runs/6427842952?check_suite_focus=true

+ This PR still two commits, please squash them. https://github.com/percona/pg_stat_monitor/pull/221/commits

Kai

**Comment by ibrarahmad** [comment]
I have updated the TAP test cases and SQUASH the commits.

**Review by capri1989 — APPROVED** [review]
LGTM

**Pull request merged**
