### PR TITLE
PG-459 Documented changes in setting pgsm sta

### PR DESCRIPTION
**Pull request by nastena1606**
rt time

modified:   docs/USER_GUIDE.md

### CODE REVIEW

**Review by capri1989 — APPROVED** [review]
LGTM

**Review by EngineeredVirus — APPROVED** [review]
LGTM

**Comment by capri1989** [comment]
I just realized that this PR was against the REL_1_STABLE branch instead of main. We need to cherry pick this one into main.

**Comment by capri1989** [comment]
https://github.com/percona/pg_stat_monitor/pull/276

**Pull request merged**
