### PR TITLE
PMM-8894 Add missed property to notes from settings to enable query plans.

### PR DESCRIPTION
**Pull request by JiriCtvrtka**

### CODE REVIEW

**Comment by ibrarahmad** [comment]
@JiriCtvrtka  please resolve the conflicts

**Comment by ibrarahmad** [comment]
@JiriCtvrtka Please resolve conflicts

**Comment by ibrarahmad** [comment]
There are conflicts in Pull request.

**Comment by JiriCtvrtka** [comment]
Closed since there are no more list of configuration parameters.

**Pull request closed without merging**
